#!/bin/bash

EXEC="./$1"
TEST_FOLDER="tests"
OUT_FILE=".out"

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

echo "Starting tests..."

check_success() {
	desired_file=$1
	if [ -f $desired_file ]; then
		cmp --silent $OUT_FILE $desired_file
		res=$?
		#echo "CMP: $res"
		#echo "RES:"
		#cat $OUT_FILE
		#echo "DES:"
		#cat $desired_file
		if [ $res -eq "0" ]; then
			return 1
		else
			return 0
		fi
	else
		return 0
	fi
}

for input in `ls $TEST_FOLDER/*.in | sort -V`; do
	printf "Running test: $input"
	$EXEC < $input > $OUT_FILE &
	pid=$!
	#printf "\nInput:\n"
	#cat $input
	#printf "Output:\n"
	#cat $OUT_FILE
	printf " : "
	wait $pid
	desired_file="${input%.*}.out"
	check_success $desired_file
	success=$?
	if [ $success -eq "1" ]; then
		printf "${GREEN}Success${NC}\n"
	else
		printf "${RED}Failed${NC}\n"
	fi
done

if [ -f $OUT_FILE ]; then
	rm $OUT_FILE
fi
